#!/bin/bash
# Generated by mcptoskill — https://mcptoskill.com
# Server: Notion MCP v1.2.0
# URL: https://mcp.notion.com/mcp
# OAuth: notion (auto-refresh enabled)
set -euo pipefail

TOOL_NAME="${1:?Usage: mcp-notion.sh <tool-name> '<json-args>'}"
ARGS="${2:-}"
[ -z "$ARGS" ] && ARGS='{}'
MCP_URL="https://mcp.notion.com/mcp"
TOKEN_FILE="C:\Users\adria\.claude\mcptoskill\tokens/mcp-notion.json"

# --- Token management ---

read_token() {
  if [ ! -f "$TOKEN_FILE" ]; then
    echo "Error: token file not found at $TOKEN_FILE" >&2
    echo "Re-run: npx @filiksyos/mcptoskill https://mcp.notion.com/mcp" >&2
    exit 1
  fi
  ACCESS_TOKEN=$(jq -r '.access_token' "$TOKEN_FILE")
}

is_expired() {
  local expires_at
  expires_at=$(jq -r '.expires_at // 0' "$TOKEN_FILE")
  if [ "$expires_at" = "null" ] || [ "$expires_at" = "0" ]; then
    return 1
  fi
  local now
  now=$(date +%s)
  [ "$now" -ge "$((expires_at - 60))" ]
}

refresh_token_flow() {
  local rt token_endpoint client_id
  rt=$(jq -r '.refresh_token // empty' "$TOKEN_FILE")
  token_endpoint=$(jq -r '.token_endpoint // empty' "$TOKEN_FILE")
  client_id=$(jq -r '.client_id // empty' "$TOKEN_FILE")

  if [ -z "$rt" ]; then
    echo "Error: no refresh token — re-run: npx @filiksyos/mcptoskill https://mcp.notion.com/mcp" >&2
    exit 1
  fi

  REFRESH_BODY="grant_type=refresh_token&refresh_token=$rt&client_id=$client_id"

  local resp
  resp=$(curl -s -X POST "$token_endpoint" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "$REFRESH_BODY")

  local new_at
  new_at=$(echo "$resp" | jq -r '.access_token // empty')
  if [ -z "$new_at" ]; then
    echo "Error: token refresh failed — re-run: npx @filiksyos/mcptoskill https://mcp.notion.com/mcp" >&2
    echo "$resp" >&2
    exit 1
  fi

  local new_rt new_exp now new_expires_at
  new_rt=$(echo "$resp" | jq -r '.refresh_token // empty')
  new_exp=$(echo "$resp" | jq -r '.expires_in // 3600')
  now=$(date +%s)
  new_expires_at=$((now + new_exp))

  jq --arg at "$new_at" \
     --arg rt "${new_rt:-$rt}" \
     --argjson ea "$new_expires_at" \
     '.access_token=$at | .refresh_token=$rt | .expires_at=$ea' \
     "$TOKEN_FILE" > "${TOKEN_FILE}.tmp" && mv "${TOKEN_FILE}.tmp" "$TOKEN_FILE"
  chmod 600 "$TOKEN_FILE"
}

ensure_fresh_token() {
  read_token
  if is_expired; then
    refresh_token_flow
    read_token
  fi
}

ensure_fresh_token

# --- MCP call ---

AUTH_HEADER="Authorization: Bearer $ACCESS_TOKEN"

TEMP_HEADERS=$(mktemp)
curl -s -X POST "$MCP_URL" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json, text/event-stream" \
  -H "$AUTH_HEADER" \
  -D "$TEMP_HEADERS" \
  -d '{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"mcptoskill","version":"0.1.0"}}}' > /dev/null

SESSION_ID=$(grep -i "^mcp-session-id:" "$TEMP_HEADERS" | awk '{print $2}' | tr -d '\r' || true)
rm -f "$TEMP_HEADERS"

if [ -n "$SESSION_ID" ]; then
  RESPONSE=$(curl -s -X POST "$MCP_URL" \
    -H "Content-Type: application/json" \
    -H "Accept: application/json, text/event-stream" \
    -H "$AUTH_HEADER" \
    -H "Mcp-Session-Id: $SESSION_ID" \
    -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"$TOOL_NAME\",\"arguments\":$ARGS}}")
else
  RESPONSE=$(curl -s -X POST "$MCP_URL" \
    -H "Content-Type: application/json" \
    -H "Accept: application/json, text/event-stream" \
    -H "$AUTH_HEADER" \
    -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"$TOOL_NAME\",\"arguments\":$ARGS}}")
fi

# Handle SSE format (event: message / data: {...}) or plain JSON
if echo "$RESPONSE" | grep -q '^data: '; then
  echo "$RESPONSE" | grep '^data: ' | tail -1 | sed 's/^data: //'
else
  echo "$RESPONSE"
fi
